config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  namespace :api do
    namespace :v1 do
      post :auth, to: 'authentication#create'
      resources :users, only: [] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end

  resources :users, only:[:index, :show] do
    resources :posts, only:[:index, :new, :show, :create, :destroy] do
      resources  :comments, only:[:index, :new, :create, :destroy]
      resources  :likes, only:[:new, :create]
    end
  end

  root "users#index"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, comparison: { greater_than_or_equal_to: 0 }

  before_destroy -> { User.find_by(id: author.id).decrement!(:posts_counter) }
  before_save -> { User.find_by(id: author.id).increment!(:posts_counter) }

  def five_most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApiController
  def index
    @user = User.find(params[:user_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: %i[index show]

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    @post.likes_counter = 0
    @post.comments_counter = 0

    if @post.save
      redirect_to user_posts_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    @post.likes.destroy_all
    @post.comments.destroy_all
    @post.destroy

    respond_to do |format|
      format.html { redirect_to "/users/#{params[:user_id]}/posts", notice: 'Post was destroyed successfully.' }
      format.json { head :no_content }
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/views/posts/index.html.erb
<div class="user">

 <%= render 'partials/user', user: @user%>

 <% @posts.includes(:comments).each do |post| %>

    <%= render 'partials/post', post: post%>



    <div class='user-text'>
      <%post.five_most_recent_comments.each do |postcomment| %>
        <p>
          <span><%= postcomment.author.name %></span>:
          <span><%= postcomment.text %></span>
        </p>

      <% end %>
    </div>
   <a href="/users/<%= @user.id%>/posts/<%= post.id%>" ><button>View post #<%= post.id%></button></a>

  <% end %>

  <a href="/users/<%= @user.id%>/posts/new" ><button style="margin-top: 10px;">Create new post</button></a>
  <div class='btn-paginate'>
  <button>Pagination</button>
  </div>
</div>

app/views/posts/new.html.erb
<div class='user'>

    <% if @post.errors.any? %>
        <div class='error'>
            <h2><%= pluralize(@post.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
                <% @post.errors.each do |error| %>
                    <li><%= error.full_message %></li>
                <% end %>
            </ul>
        </div>
    <% end%>



    <%= form_with url:"/users/#{params[:user_id]}/posts", model: @post do |form| %>
        <div class='user-text-field'>
            <%= form.label :title %>
            <%= form.text_field :title %>
        </div>

        <div class='user-text-field'>
            <%= form.label :text %>
            <%= form.text_area :text, size: '60x10' %>
        </div>

        <%= form.submit 'Create A New Post'%>
    <% end %>

</div>

app/views/posts/show.html.erb
<div class="user">

 <div class='user-text'>
    <div class='post-detail'>
      <p>Post #<%=@post.id %> by <%=@post.author.name %></p>
      <p>
        Comments:<span><%= @post.comments_counter %></span>,
        Likes: <span><%= @post.likes_counter %></span>
      </p>
    </div>
    <p><%=@post.text %></p>
  </div>


  <div class='user-text'>
    <%@post.five_most_recent_comments.each do |comment| %>
      <p>
        <span><%= comment.author.name %></span>:
        <span><%= comment.text %></span>
        <% if can? :destroy, comment %>
          <%= form_with(model: @comment, url: user_post_comment_path(params[:user_id], @post), method: :delete, data: { confirm: "Are you sure?" }) do |form| %>
            <%= form.hidden_field :comment_info, value: "#{comment.id}" %>
            <%= form.submit "Destroy Comment" %>
          <% end %>
        <% end %>
      </p>
    <% end %>
  </div>

  <% if can? :destroy, @post %>
    <%= form_with(model: @post, url: user_post_path(params[:user_id], @post), method: :delete, data: { confirm: "Are you sure?" }) do |form| %>
      <%= form.submit "Destroy Post" %>
    <% end %>
  <% end %>

  <a href='/users/<%= @user.id%>/posts/<%= @post.id%>/likes/new' ><button style="margin-left: 150px;">Like this post</button></a>
  <a href='/users/<%= @user.id%>/posts/<%= @post.id%>/comments/new' ><button style="margin-left: 150px;">Add a comment</button></a>

</div>